
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\HOC TAP\KLTN\GUI\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("594x368")
window.configure(bg = "#FBFBFB")


canvas = Canvas(
    window,
    bg = "#FBFBFB",
    height = 368,
    width = 594,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    304.0,
    184.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    167.5,
    115.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#BFD7EE",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=45.0,
    y=91.0,
    width=245.0,
    height=46.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=167.0,
    y=161.0,
    width=122.0,
    height=49.0
)

canvas.create_text(
    32.0,
    47.0,
    anchor="nw",
    text="TYPE YOUR NAME",
    fill="#F70F0F",
    font=("Georgia", 24 * -1,"bold")
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=32.0,
    y=159.0,
    width=122.0,
    height=49.0
)
window.resizable(False, False)
window.mainloop()
