
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\HOC TAP\KLTN\GUI\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("594x368")
window.configure(bg = "#FBFBFB")


canvas = Canvas(
    window,
    bg = "#FBFBFB",
    height = 368,
    width = 594,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    304.0,
    184.0,
    image=image_image_1
)

canvas.create_text(
    80.0,
    115.0,
    anchor="nw",
    text=" PUT YOUR HAND ",
    fill="#DF1717",
    font=("Georgia", 26 * -1,"bold")
)

canvas.create_text(
    85.0,
    168.0,
    anchor="nw",
    text="ABOVE THE BOX",
    fill="#DF1717",
    font=("Georgia", 26 * -1,"bold")
)
window.resizable(False, False)
window.mainloop()
